### ISSUE TITLE
Issue with IP address

### ISSUE THREAD

**Issue by jakekerry** [avseng/LiveStramingCamera#1]
Ive double checked all my work and cant figure out why when i run camera.py it doesnt assign me an IP adress. Any ideas??
Here is what i get:

~ $ python3 camera.py
 * Serving Flask app "__name__" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 
Shouldnt the IP be sonmething other than 0.0.0.0? LOL

**Comment by avseng** [comment]
0.0.0.0 meams it will automatically assign system network ip globally and u
can access over network. Ur code is working fine, u can try accesing the
camera with rpi ip..it will work..

**Comment by jakekerry** [comment]
oh ok so replace the 0.0.0.0 in the code with the pi IP?

**Comment by jakekerry** [comment]
Thanks @avseng !! that worked :)
